# Generated by Django 3.2.6 on 2021-09-11 00:24

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'そのユーザー名は既に使われています。'}, help_text='ユーザ名は', max_length=50, unique=True, validators=[account.models.CustomUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email_address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('usl', models.URLField(verbose_name='homepage_url')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner_id')),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
    ]
