# Generated by Django 3.2.6 on 2021-09-11 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210911_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='usl',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
