# Generated by Django 3.2.6 on 2021-09-15 10:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organizer_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'そのユーザー名は既に使われています。'}, help_text='ユーザ名は50文字以下で、英数字,もしくはアンダーバー(_)のみが使用できます。', max_length=50, unique=True, validators=[account.models.CustomUsernameValidator()], verbose_name='username'),
        ),
    ]
