version: '3'

services:
  db:
    image: mariadb:10.6.4
    container_name: db
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      app-network:
          ipv4_address: 172.100.0.2
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks: 
      app-network:
        ipv4_address: 172.100.0.3
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    tty: true
    networks:
      app-network:
          ipv4_address: 172.100.0.5
networks:
  app-network:
    ipam: 
      driver: default
      config: 
        - subnet: 172.100.0.0/24