# Generated by Django 3.2.6 on 2021-09-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('url', models.URLField(blank=True, null=True, verbose_name='homepage_url')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owenr')),
            ],
            options={
                'db_table': 'place',
            },
        ),
    ]
