# Generated by Django 3.2.6 on 2021-09-27 12:16

from django.db import migrations, models
import django.db.models.deletion
import race.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='チーム名')),
                ('num', models.CharField(blank=True, max_length=10, validators=[race.models.NumValidator()], verbose_name='ゼッケンNo')),
                ('is_dns', models.BooleanField(default=False, verbose_name='DNS')),
                ('is_dnf', models.BooleanField(default=False, verbose_name='DNF')),
            ],
        ),
        migrations.CreateModel(
            name='RaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ステータス')),
            ],
            options={
                'db_table': 'racestatus',
            },
        ),
        migrations.CreateModel(
            name='RaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='レースタイプ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.category', verbose_name='レースカテゴリ')),
            ],
            options={
                'db_table': 'racetype',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='レース名')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ホームページURL')),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='その他情報')),
                ('is_regulationsetuped', models.BooleanField(default=False)),
                ('is_teamrace', models.BooleanField(default=False, verbose_name='チームレース')),
                ('team_member_count_min', models.IntegerField(default=0, verbose_name='チーム最小人数')),
                ('team_member_count_max', models.IntegerField(default=0, verbose_name='チームメンバー最大人数')),
                ('is_heat', models.BooleanField(default=False, verbose_name='ヒート制')),
                ('heat_count', models.IntegerField(default=0, verbose_name='ヒート数')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organizer', verbose_name='主催者')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='開催地')),
                ('racetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.racetype', verbose_name='レースタイプ')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.racestatus', verbose_name='ステータス')),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptime', models.TimeField(null=True, verbose_name='ラップタイム')),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.entrant', verbose_name='エントラント')),
            ],
        ),
        migrations.CreateModel(
            name='Entrant_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='エントリー名')),
                ('belonging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.entrant', verbose_name='所属エントラント')),
            ],
        ),
        migrations.AddField(
            model_name='entrant',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='参加レース'),
        ),
    ]
