# Generated by Django 3.2.6 on 2021-09-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.racestatus', verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='race',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ホームページURL'),
        ),
    ]
