# Generated by Django 3.2.6 on 2021-09-21 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_auto_20210917_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='開催日'),
            preserve_default=False,
        ),
    ]
