# Generated by Django 3.2.6 on 2021-10-06 08:54

from django.db import migrations, models
import race.models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_lap_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='num',
            field=models.CharField(max_length=10, validators=[race.models.NumValidator()], verbose_name='ゼッケンNo'),
        ),
    ]
