# Generated by Django 3.2.6 on 2021-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_alter_entrant_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='start_at',
            field=models.DateTimeField(null=True, verbose_name='レース開始日時'),
        ),
    ]
