# Generated by Django 3.2.6 on 2021-09-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_race_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='その他情報'),
        ),
    ]
