# Generated by Django 3.2.6 on 2021-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_race_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='regulations',
            field=models.JSONField(blank=True, null=True, verbose_name='レギュレーション'),
        ),
    ]
