# Generated by Django 3.2.6 on 2021-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_race_regulations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='regulations',
        ),
        migrations.AddField(
            model_name='race',
            name='heat_count',
            field=models.IntegerField(default=0, verbose_name='ヒート数'),
        ),
        migrations.AddField(
            model_name='race',
            name='is_heat',
            field=models.BooleanField(default=False, verbose_name='ヒート制'),
        ),
        migrations.AddField(
            model_name='race',
            name='is_teamrace',
            field=models.BooleanField(default=False, verbose_name='チームレース'),
        ),
        migrations.AddField(
            model_name='race',
            name='team_member_count_max',
            field=models.IntegerField(default=0, verbose_name='チームメンバー最大人数'),
        ),
        migrations.AddField(
            model_name='race',
            name='team_member_count_min',
            field=models.IntegerField(default=0, verbose_name='チーム最小人数'),
        ),
    ]
