# Generated by Django 3.2.6 on 2021-09-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0007_race_is_regulationsetuped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='チーム名')),
                ('num', models.CharField(blank=True, max_length=10, null=True, verbose_name='ゼッケンNo')),
                ('is_dns', models.BooleanField(default=False, verbose_name='DNS')),
                ('is_dnf', models.BooleanField(default=False, verbose_name='DNF')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='参加レース')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptime', models.TimeField(null=True, verbose_name='ラップタイム')),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.entrant', verbose_name='エントラント')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='レース')),
            ],
        ),
        migrations.CreateModel(
            name='Entrant_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='エントリー名')),
                ('belonging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.entrant', verbose_name='所属エントラント')),
            ],
        ),
    ]
