# Generated by Django 3.2.6 on 2021-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_entrant_entrant_member_lap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='num',
            field=models.CharField(blank=True, default=100, max_length=10, verbose_name='ゼッケンNo'),
            preserve_default=False,
        ),
    ]
